package com.healthyreal.be.api.entity.userInfo;

public enum GoalType {
	WEIGHT_LOSS, MUSCLE_GAIN, STAMINA_IMPROVEMENT, FLEXIBILITY_IMPROVEMENT,
	BODY_SHAPE_IMPROVEMENT, BALANCE_IMPROVEMENT, LIFESTYLE_IMPROVEMENT,
	HEALTH_IMPROVEMENT, BODY_PROFILE, OTHER
}
